### PR TITLE
Update cssjanus.js

### PR DESCRIPTION
**Pull request by reedy**
Brings in minor regex changes from https://github.com/cssjanus/php-cssjanus/pull/19

Escaping differences are already present

### CODE REVIEW

**Comment by jdforrester** [comment]
Should we have tests?

**Comment by reedy** [comment]
```
Warning: Invalid regular expression: /(\/\*\!?\s*@noflip\s*\*\/(?!((?:[_a-z0-9-]|[^\u0020-\u007e]|(?:(?:(?:\\[0-9a-f]{1,6})(?:\r\n|\s)?)|\\[^\r\n\f0-9a-f]))|\r?\n|\s|#|\:|\.|\,|\+|>|\(|\)|\[|\]|=|\*=|~=|\^=|'[^']*'])*+{)[^;}]+;?)/: 
```

**Comment by reedy** [comment]
The PHP changes aren't compatible for the js version... I guess #74 covers this difference (for now at least)

**Comment by Krinkle** [comment]
Yep. Nothing we can do at the moment. Closing for now.

**Pull request closed without merging**
