### PR TITLE
Add patterns for translate(x[,y,z]) and translateX(x)

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by Krinkle** [comment]
I'll first add a visual test on the demo to make it easier to see the problem and confirm the fix.

**Comment by edg2s** [comment]
Visual test?

**Comment by Krinkle** [comment]
See <https://cssjanus.github.io/demo/>. I've verified the fix to behave as one would expected. Sometimes the flipping of the values is not entirely intuitive. A visual confirmation makes it easier to review.

**Comment by Krinkle** [comment]
We may want to limit this to values in transforms, but then we need to take care to properly support multiple values as well such as `transform: rotate(10deg) translateX(10px) translateY(5px);`.

**Comment by yonatan** [comment]
For multiple values I think something like "transform: scaleX(-1) ...original transformations... scaleX(-1)" will do the trick.

**Comment by yonatan** [comment]
For multiple arbitrary transformations (rotate, skew, matrix, etc) something like "transform: scaleX(-1) [original transformations] scaleX(-1)" should do the trick. As in:

LTR: http://codepen.io/anon/pen/WRZJyK
RTL: http://codepen.io/anon/pen/dNVejp

The transform-origin property can be a problem when unit lengths are involved. Might be possible with CSS calc.

**Comment by edg2s** [comment]
We should also tag 1.1.4 so PHP can use the new tests.

**Comment by edg2s** [comment]
Added match for transform property - this now only matches one 'transform' per rule, but having multiple transformX's or a transform+transformX would be nonsensical.

**Pull request merged**
