### PR TITLE
border-radius with !important produces wrong output

### PR DESCRIPTION
**Pull request by ocean90**
This PR adds a test for `div { border-radius: 0 !important }` where the expected output would be the same. But you get `div { border-radius: !important 0 }`.

Another added test is `div { border-radius: 8px 7px !important }` which should output `div { border-radius: 7px 8px !important }`, but you get `div { border-radius: 7px 8px } !important`.

Related: https://core.trac.wordpress.org/ticket/29038

### CODE REVIEW

**Comment by ocean90** [comment]
@trevorparscal I've updated this pull request to support the recent changes.

**Comment by Krinkle** [comment]
@ocean90 Thanks! I'll get it merged this week.

**Comment by ntwb** [comment]
@Kringle Any chance of maybe merging this this week? :wink:

**Comment by Krinkle** [comment]
@ocean90 I made a few minor changes (adjust indentation of `borderRadiusRegExp`, document border-radius syntax, capitalise `@param {Array}`, and added tests for four-values with slashes). I also simplified the implementation in follow-up commit 1faff3fdcd4. It's slightly less performant due to `Array#slice` and `Array#filter` overhead, but makes it a lot simpler.

@ntwb Done!

**Comment by ntwb** [comment]
Thanks :)

**Comment by ocean90** [comment]
Thanks @Krinkle!

**Pull request closed without merging**
